### ISSUE TITLE
Please share the data files

### ISSUE THREAD

**Issue by johnhhu2020** [AmoDinho/datacamp-python-data-science-track#9]
In all the courses of this DS track, containing many data files, such as this one, albeck_gene_expression.mat.  So we can do the analysis on our own environment. Can you please share those files? Thanks

**Comment by AmoDinho** [comment]
Hi @johnhhu2020, Unfortunately I was unable to download the those files :/

**Comment by johnhhu2020** [comment]
never mind and thank you for the reply
